[package]
name = "underflow-main"
# description.workspace = true
edition.workspace = true
# license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
macroquad = { workspace = true }
