[workspace]
resolver = "2"
members = ["underflow-core", "underflow-main"]

[workspace.package]
# description = ""
edition = "2024"
# license = "MIT"
repository = "https://github.com/sjfhsjfh/underflow"
version = "0.0.2"

[workspace.dependencies]
macroquad = "0.4.13"
serde = { version = "1.0.219", features = ["derive"] }
either = "1.15.0"