[package]
name = "underflow-core"
# description.workspace = true
edition.workspace = true
# license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true }
either = { workspace = true }