name: Cargo Test

on:
  push: {}
  pull_request: {}

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          rustup toolchain install stable
          rustup default stable

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with: 
          cache-on-failure: "true"
          cache-all-crates: "true"

      - name: Run tests
        run: cargo test